### ISSUE TITLE
C support

### ISSUE THREAD

**Issue by ethan-leba** [ethan-leba/tree-edit#54]
### TODO:

  * [ ] Complete `tree-edit-syntax-snippets` for all nodes
  * [ ] Add keybindings in `tree-edit-nodes` for all nodes
  * [ ] Address disabled tests in `tests/test-c.el`
